apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  labels:
    app: frontend-external
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      # the node port must be unique in terms of a single machine
      nodePort: 30002
      name: http
  selector:
    app: frontend-ds