cart:
    build: server/Cart-Service/Cart-Service/
    ports:
        - "8084:8084"
catalog:
    build: server/Catalog/Catalog-Service/
    ports:
        - "8081:8081"
shipping:
    build: server/Shipping/Shipping-Service/
    ports:
        - "8082:8082"
checkout:
    build: server/Checkout-Service/Checkout-Service/
    ports:
        - "8083:8083"
    links:
        - catalog
        - shipping
        - cart
frontend:
    build: client/
    ports:
        - "4200:4200"
    