apiVersion: v1
kind: Service
metadata:
  name: catalog-external
  labels:
    app: catalog-external
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      # the node port must be unique in terms of a single machine
      nodePort: 30001
      name: http
  selector:
    app: catalog-ds