apiVersion: v1
kind: Service
metadata:
  name: shipping-external
  labels:
    app: shipping-external
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8083
      # the node port must be unique in terms of a single machine
      nodePort: 30004
      name: http
  selector:
    app: shipping-ds
