apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-ds
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-ds
  template:
    metadata:
      name: checkout-ds
      labels:
        app: checkout-ds
    spec:
      containers:
      - name: checkout-ds
        image: yggdrahl/catalog:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
