apiVersion: v1
kind: Service
metadata:
  name: checkout-external
  labels:
    app: checkout-external
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8084
      # the node port must be unique in terms of a single machine
      nodePort: 30005
      name: http
  selector:
    app: checkout-ds
